defaults:
  app:
    keyPrefix: 'ec2-manager:'
    instancePubKey: !env AWS_INSTANCE_PUBKEY
    spotPollDelay: 25 # (seconds)
    houseKeepingPollDelay: 86400 # (seconds) 1 day
    maxInstanceLifeHours: 96 # (hours)
    regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
    queueName: 'ec2-events'
    ruleName: 'ec2-instance-state-transitions'
    publishMetadata: false
    pricingPollDelay: 900 # (seconds) 15 minutes
    pricingTimePeriod: 30 # (seconds)
  ec2:
    apiVersion: 2014-01-01
  sqs:
    apiVersion: 2012-11-05
  cwe:
    apiVersion: 2015-10-07
  aws:
    accessKeyId: !env AWS_ACCESS_KEY_ID
    secretAccessKey: !env AWS_SECRET_ACCESS_KEY
    maxRetries: 10
  postgres:
    databaseUrl: !env DATABASE_URL
  server:
    port: 5555
    publicUrl: localhost:5555
    baseUrl: 'http://localhost:5555/v1'
    env: development
    forceSSL: false
    trustProxy: false
  monitor:
    project: ec2-manager
    mock: true
  taskcluster:
    authBaseUrl: https://auth.taskcluster.net/v1
    queueBaseUrl: https://queue.taskcluster.net/v1
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN
development:
  app:
    keyPrefix: 'aws-provisioner-dev:'
production:
  server:
    port: !env:number PORT
    env: production
    forceSSL: true
    trustProxy: true
    baseUrl: 'https://ec2-manager.herokuapp.com/v1'
  app:
    keyPrefix: 'aws-provisioner-v1-managed:'
    publishMetadata: true
  postgres:
    maxClients: 110
  monitor:
    project: ec2-manager
    mock: false
staging:
  server:
    port: !env:number PORT
    env: production
    forceSSL: true
    trustProxy: true
    baseUrl: 'https://ec2-manager-staging.herokuapp.com/v1'
  app:
    keyPrefix: 'ec2-manager-staging:'
    publishMetadata: true
  postgres:
    maxClients: 10
  monitor:
    project: ec2-manager-staging
    mock: false
test:
  app:
    keyPrefix: 'ec2-manager-test:'
    instancePubKey: 'ssh-rsa pubkeydata'
    spotPollDelay: 200
